######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 29 06:41:49 2021
######################################################################

TEMPLATE = app
TARGET = hello_qt
DEPENDPATH += . \
              src \
INCLUDEPATH += .

# Input
SOURCES += src/main.cpp \

